#!/bin/sh

if [ ! -f /run/fredl_bt_ready ]; then
	echo "Waiting until bt is ready"
	exit 0
fi

echo "RFKILL state: $RFKILL_STATE"

PATCHRAM_ARGS="--patchram /vendor/firmware/BCM4345C0.hcd \
               --enable_lpm \
               --no2bytes \
               --enable_hci \
               --baudrate 3000000"


if [ "$RFKILL_STATE" == "1" ]; then
	/usr/bin/brcm_patchram_plus $PATCHRAM_ARGS /dev/ttyHS0 &
	BRCM_PR_P_PID=$!
	echo $BRCM_PR_P_PID > /run/bt_patchram_pid
elif [ "$RFKILL_STATE" == "0" ]; then
	kill -9 `cat /run/bt_patchram_pid`
	rm /run/bt_patchram_pid
fi

exit 0
